#!/bin/sh

echo "\033[4;32m\033[1;32mUSAGE COMMANDS:\033[0m\033[1;32m
1. ENTER once to run the command
2. ENTER twice to skip to next question
3. CONTROL C to exit\033[0m\n"

echo "\033[1;33m1. List the network interface names.\033[0m"
	echo "ifconfig -l | tr \" \" \"\\\n\""
read -p ""
	ifconfig -l | tr " " "\n" 
read -p "" ; ./02

# These are your network interfaces. Some are physical interfaces, and others are logical (virtual) interfaces.
