#!/bin/sh

echo "\033[1;33m7. Query an external DNS server on the slash16.org domain name.\033[0m"
	echo "nslookup slash16.org 8.8.8.8"
read -p ""
	nslookup slash.org 8.8.8.8 | tail -r | tail -n +2 | tail -r
read -p ""; ./08
