#!/bin/sh

echo "\033[1;33m9. Find the external IP(s) of 42.fr\033[0m"
	echo "nslookup 42.fr | grep \"Address:\" | tail -n 3 | awk '{ print \$2 }'"
read -p ""
	nslookup 42.fr | grep "Address:" | tail -n 3 | awk '{ print $2 }'
read -p "" ; ./10
