#!/bin/sh

# Use the output of the previous command to find the name and IP address 
# of the device that makes the link between you (local network) and the 
# outside world

IPADDR="$(ifconfig en0 | awk '/inet / {print $2 }')"
PCNAME="$(hostname | sed "s/.42.us.org/""/")"

echo "\033[1;33m11. The device that makes the link between \033[1;31m$PCNAME\033[1;33m \
with IP of \033[1;31m$IPADDR\033[1;33m and the outside world\033[0m"
	echo "\033[1;33mName:\033[0m nat"
	echo "\033[1;33mIP:\033[0m 10.90.1.11"
read -p "" ; ./12
