#!/bin/sh

SERVER=10.51.1.253

echo "\033[1;33m12. Check that the server with the $SERVER IP address reachable:\033[0m"
echo "if ping -c1 $SERVER 1>/dev/null 2>/dev/null
then
	echo \"$SERVER \033[1;32m[REACHABLE]\033[0m\"
else
	echo \"$SERVER \033[1;31m[NOT REACHABLE]\033[0m\"
fi"
read -p ""
if ping -c1 $SERVER 1>/dev/null 2>/dev/null
then
	echo "$SERVER \033[1;32m[REACHABLE]\033[0m"
else
	echo "$SERVER \033[1;31m[NOT REACHABLE]\033[0m"
fi
read -p "" ; ./13
