#!/bin/sh

IPADDR="10.51.1.81"

echo "\033[1;33m14. Use the Reverse DNS to find out the name of the server linked to the $IPADDR IP adress:\033[0m"
	echo "nslookup \$IPADDR | grep \"name =\" | awk '{ print \$4 }' | rev | cut -c2- | rev"
read -p ""
	nslookup $IPADDR | grep "name =" | awk '{ print $4 }' | rev | cut -c2- | rev
read -p "" ; ./15
