#!/bin/sh

echo "\033[1;33m16. Make the intra.42.fr address reroute to 46.19.122.85:\033[0m"
	echo "sudo echo \"46.19.122.85	intra.42.fr\" >> /etc/hosts"
read -p ""
	sudo echo "46.19.122.85 intra.42.fr" >> /etc/hosts
echo "\n\033[1;33mDeduction:\033[0m The hosts file can be manually changed to reroute addresses with admin privileges."
