#!/bin/sh

echo "\033[4;32m\033[1;32mUSAGE COMMANDS:\033[0m\033[1;32m
1. ENTER to skip to next question
2. CONTROL C to exit\033[0m\n"

echo "\033[1;33m1. In what file can you find the installed version of your Debian?\033[0m"
	echo "/etc/debian_version"
echo "\n\033[1;33mDeduction:\033[0m The path to the file above contains the version code of the installed Debian system."
read -p "" ; ./02
