#!/bin/sh

echo "\033[1;33m16. Find the service which makes it possible to run specific tasks following a regular schedule\033[0m"
	echo "cron"
echo "\n\033[1;33mDeduction:\033[0m Cron is a daemon to run schedule tasks. Cron wakes up every minute and checks schedule tasks in crontable.\
	\nCrontab (CRON TABle) is a table where we can schedule such kind of repeated tasks."
read -p "" ; ./17
